apiVersion: apps/v1
kind: Deployment #Controller
metadata:
  name: nginx-deploy
  labels:
    app: nginx-deploy
  namespace: dev-team
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:      
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx-pod
        image: nginx
        ports:
          - containerPort: 80