apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-fs-vol 
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /vol01
    server: 10.105.6.66
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    namespace: default
    name: manual-fs-claim
