- name: Gathering facts
  hosts: clients
  remote_user: root
  vars_files:
    - secret.yaml   

  tasks:
  - name: create user account with plain password
    user:
      name: user4 
      password: "{{ secret | password_hash('sha512') }}"
      shell: /bin/bash
      state: present