apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-hello-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec: 
          containers:
          - name: hello 
            image: busybox
            args:
            - /bin/sh 
            - -c 
            - echo "Hello, World!"
          restartPolicy: OnFailure