apiVersion: rbac.authorization.k8s.io/v1
kind: Role #Namespace Specific
metadata:
  name: pod-log-reader
  namespace: dev-team
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - pods/log
  verbs: ["get","create","update","list","delete"]