apiVersion: apps/v1
kind: Deployment #prod env
metadata:
  name: nginx-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx-prod
        image: nginx  #in nginx.confg default worker_connections: 1024        
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-prod-config-volume
          mountPath: /etc/nginx/conf.d/   #/etc/nginx/conf.d/default.conf
        - name: nginx-prod-mime-types-volume
          mountPath: /etc/nginx/
      volumes:
      - name: nginx-prod-config-volume
        configMap:
          name: nginx-prod-config
      - name: nginx-prod-mime-types-volume
        configMap:
          name: nginx-prod-mime-types