- name: Install tree package
  hosts: clients
  remote_user: root 

  tasks:
  - name: Run apt-update
    apt: 
      update_cache: yes 

  - name: Install tree package 
    apt:
      name: tree 
      state: present