- name: Uninstall LAMP stack
  hosts: clients
  remote_user: root

  vars:
    apache_pkg: apache2 
    mysql_pkg: mariadb-server 
    mysql_service: mariadb 
    php_pkgs:
      - php 
      - php-mysql
  
  tasks:
  - name: stop apache2 service
    service:
      name: "{{ apache_pkg }}"
      state: stopped

  - name: uninstall apache2 
    apt:
      name: "{{ apache_pkg }}" 
      state: absent
  
  - name: stop mariadb service
    service:
      name: "{{ mysql_service }}"
      state: stopped

  - name: uninstall mariadb
    apt:
      name: "{{ mysql_pkg }}" 
      state: absent
  
  - name: uninstall php 
    apt:
      name: "{{ php_pkgs }}"
      state: absent