apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor
metadata:
  name: mongodb-sm 
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: mongodb-exporter
  endpoints:
  - port: metrics 
    interval: 30s