apiVersion: apps/v1 
kind: Deployment #Controller
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80